services:
  cxx2nifi:
    build:
      dockerfile: ./Dockerfile
#    image: ghcr.io/medic/cxx2nifi:latest
    environment:
      - QUERY_RESULT_FILE="/opt/app/cxx2nifi/input/result.csv"
      - FHIR_SERVER_URL="http://localhost:8080/fhir"
      - NIFI_TARGET_URL="http://locahost:8081/nifi/fhir"
    volumes:
      - ./input:/opt/app/cxx2nifi/input