cxx:
  database:
    type: "[postgresql|sqlserver]"
    host: "<hostname>"
    port: <port>
    name: "<db-name>"
    username: "<username>"
    password: "<password>"
  fhir:
    url: "[http|https]://<base-url>/fhir"
    authorization:
      basic:
        username: "<username>"
        password: "<password>"
#      oauth:
#        grantType: "<grant-type>"
#        accessTokenUrl: "[http|https]://<base-url>/path/to/request/token"
#        clientId: "<client-id>"
#        clientSecret: "<client-secret>"
  criteriaFile: "/path/to/criteria/file"
  managingOrg: "<system-uri>|<org-id-value>"
  patientIdentifierTypeCode: "<type-code>"

schedule:
  cron: "<sec-expr> <min-expr> <hour-expr> <day-expr> <mon-expr> <dow-expr>"
#  catchupFrom: "(optional) YYYY-MM-dd:HH-mm-ss"

s3:
  url: "[http|https]://<base-url>"
  bucketName: "<bucket-name-str>"
  access:
    key: "<key>"
    secret: "<secret>"
#  region: "(optional) <region-str>"
  bundleSizeLimit: <positive-number>