name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build-publish-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup prerequisites
      uses: ./.github/actions/setup

    - name: Build project with Gradle
      shell: bash
      run: ./gradlew clean build -x test

    - name: Rename JAR
      shell: bash
      run: mv build/libs/cxx2medic.jar build/libs/cxx2medic-${{ github.ref_name }}.jar

    - name: Release JAR
      uses: softprops/action-gh-release@v2
      permissions:
        contents: write
      with:
        draft: true
        generate_release_notes: true
        files:
          build/libs/cxx2medic-${{ github.ref_name }}.jar
