name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build-publish-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup prerequisites
      uses: ./.github/actions/setup

    - name: Build project
      continue-on-error: false
      uses: ./.github/actions/build-project

    - name: Publish JAR
      uses: actions/upload-artifact@v4
      with:
        name: cxx2medic-${{ github.ref_name }}.jar
        path: ${{ github.workspace }}/build/libs/cxx2medic.jar
